// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: gg20/types/messages.proto

package types

import (
	types "github.com/bloxapp/ssv-spec/dkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KGRound1Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *KGRound1Msg) Reset() {
	*x = KGRound1Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KGRound1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KGRound1Msg) ProtoMessage() {}

func (x *KGRound1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KGRound1Msg.ProtoReflect.Descriptor instead.
func (*KGRound1Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{0}
}

func (x *KGRound1Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type KGRound2Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decommitment [][]byte `protobuf:"bytes,1,rep,name=decommitment,proto3" json:"decommitment,omitempty"`
	BlindFactor  []byte   `protobuf:"bytes,2,opt,name=blind_factor,json=blindFactor,proto3" json:"blind_factor,omitempty"`
}

func (x *KGRound2Msg) Reset() {
	*x = KGRound2Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KGRound2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KGRound2Msg) ProtoMessage() {}

func (x *KGRound2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KGRound2Msg.ProtoReflect.Descriptor instead.
func (*KGRound2Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{1}
}

func (x *KGRound2Msg) GetDecommitment() [][]byte {
	if x != nil {
		return x.Decommitment
	}
	return nil
}

func (x *KGRound2Msg) GetBlindFactor() []byte {
	if x != nil {
		return x.BlindFactor
	}
	return nil
}

type KGRound3Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Share []byte `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
}

func (x *KGRound3Msg) Reset() {
	*x = KGRound3Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KGRound3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KGRound3Msg) ProtoMessage() {}

func (x *KGRound3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KGRound3Msg.ProtoReflect.Descriptor instead.
func (*KGRound3Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{2}
}

func (x *KGRound3Msg) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

type KGRound4Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment        []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	PubKey            []byte `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	ChallengeResponse []byte `protobuf:"bytes,3,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"`
}

func (x *KGRound4Msg) Reset() {
	*x = KGRound4Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KGRound4Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KGRound4Msg) ProtoMessage() {}

func (x *KGRound4Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KGRound4Msg.ProtoReflect.Descriptor instead.
func (*KGRound4Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{3}
}

func (x *KGRound4Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *KGRound4Msg) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *KGRound4Msg) GetChallengeResponse() []byte {
	if x != nil {
		return x.ChallengeResponse
	}
	return nil
}

type KeygenMsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round1 *KGRound1Msg `protobuf:"bytes,1,opt,name=round1,proto3" json:"round1,omitempty"`
	Round2 *KGRound2Msg `protobuf:"bytes,2,opt,name=round2,proto3" json:"round2,omitempty"`
	Round3 *KGRound3Msg `protobuf:"bytes,3,opt,name=round3,proto3" json:"round3,omitempty"`
	Round4 *KGRound4Msg `protobuf:"bytes,4,opt,name=round4,proto3" json:"round4,omitempty"`
}

func (x *KeygenMsgBody) Reset() {
	*x = KeygenMsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMsgBody) ProtoMessage() {}

func (x *KeygenMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMsgBody.ProtoReflect.Descriptor instead.
func (*KeygenMsgBody) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{4}
}

func (x *KeygenMsgBody) GetRound1() *KGRound1Msg {
	if x != nil {
		return x.Round1
	}
	return nil
}

func (x *KeygenMsgBody) GetRound2() *KGRound2Msg {
	if x != nil {
		return x.Round2
	}
	return nil
}

func (x *KeygenMsgBody) GetRound3() *KGRound3Msg {
	if x != nil {
		return x.Round3
	}
	return nil
}

func (x *KeygenMsgBody) GetRound4() *KGRound4Msg {
	if x != nil {
		return x.Round4
	}
	return nil
}

//
// It has the same shape as base.Message except the data is parsed into KeygenMsgBody
type ParsedKGMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *types.MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body      *KeygenMsgBody       `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature []byte               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ParsedKGMessage) Reset() {
	*x = ParsedKGMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedKGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedKGMessage) ProtoMessage() {}

func (x *ParsedKGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedKGMessage.ProtoReflect.Descriptor instead.
func (*ParsedKGMessage) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ParsedKGMessage) GetHeader() *types.MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedKGMessage) GetBody() *KeygenMsgBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ParsedKGMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RsRound1Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *RsRound1Msg) Reset() {
	*x = RsRound1Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsRound1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsRound1Msg) ProtoMessage() {}

func (x *RsRound1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsRound1Msg.ProtoReflect.Descriptor instead.
func (*RsRound1Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{6}
}

func (x *RsRound1Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type RsRound2Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RsRound2Msg) Reset() {
	*x = RsRound2Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsRound2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsRound2Msg) ProtoMessage() {}

func (x *RsRound2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsRound2Msg.ProtoReflect.Descriptor instead.
func (*RsRound2Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{7}
}

type RsRound3Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decommitment [][]byte `protobuf:"bytes,1,rep,name=decommitment,proto3" json:"decommitment,omitempty"`
	BlindFactor  []byte   `protobuf:"bytes,2,opt,name=blind_factor,json=blindFactor,proto3" json:"blind_factor,omitempty"`
}

func (x *RsRound3Msg) Reset() {
	*x = RsRound3Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsRound3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsRound3Msg) ProtoMessage() {}

func (x *RsRound3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsRound3Msg.ProtoReflect.Descriptor instead.
func (*RsRound3Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RsRound3Msg) GetDecommitment() [][]byte {
	if x != nil {
		return x.Decommitment
	}
	return nil
}

func (x *RsRound3Msg) GetBlindFactor() []byte {
	if x != nil {
		return x.BlindFactor
	}
	return nil
}

type RsRound4Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Share []byte `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
}

func (x *RsRound4Msg) Reset() {
	*x = RsRound4Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsRound4Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsRound4Msg) ProtoMessage() {}

func (x *RsRound4Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsRound4Msg.ProtoReflect.Descriptor instead.
func (*RsRound4Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RsRound4Msg) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

type RsRound5Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment        []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	PubKey            []byte `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	ChallengeResponse []byte `protobuf:"bytes,3,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"`
}

func (x *RsRound5Msg) Reset() {
	*x = RsRound5Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsRound5Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsRound5Msg) ProtoMessage() {}

func (x *RsRound5Msg) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsRound5Msg.ProtoReflect.Descriptor instead.
func (*RsRound5Msg) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RsRound5Msg) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *RsRound5Msg) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *RsRound5Msg) GetChallengeResponse() []byte {
	if x != nil {
		return x.ChallengeResponse
	}
	return nil
}

type ResharingMsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round1 *RsRound1Msg `protobuf:"bytes,1,opt,name=round1,proto3" json:"round1,omitempty"`
	Round2 *RsRound2Msg `protobuf:"bytes,2,opt,name=round2,proto3" json:"round2,omitempty"`
	Round3 *RsRound3Msg `protobuf:"bytes,3,opt,name=round3,proto3" json:"round3,omitempty"`
	Round4 *RsRound4Msg `protobuf:"bytes,4,opt,name=round4,proto3" json:"round4,omitempty"`
	Round5 *RsRound5Msg `protobuf:"bytes,5,opt,name=round5,proto3" json:"round5,omitempty"`
}

func (x *ResharingMsgBody) Reset() {
	*x = ResharingMsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResharingMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResharingMsgBody) ProtoMessage() {}

func (x *ResharingMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResharingMsgBody.ProtoReflect.Descriptor instead.
func (*ResharingMsgBody) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ResharingMsgBody) GetRound1() *RsRound1Msg {
	if x != nil {
		return x.Round1
	}
	return nil
}

func (x *ResharingMsgBody) GetRound2() *RsRound2Msg {
	if x != nil {
		return x.Round2
	}
	return nil
}

func (x *ResharingMsgBody) GetRound3() *RsRound3Msg {
	if x != nil {
		return x.Round3
	}
	return nil
}

func (x *ResharingMsgBody) GetRound4() *RsRound4Msg {
	if x != nil {
		return x.Round4
	}
	return nil
}

func (x *ResharingMsgBody) GetRound5() *RsRound5Msg {
	if x != nil {
		return x.Round5
	}
	return nil
}

//
// It has the same shape as base.Message except the data is parsed into KeygenMsgBody
type ParsedRsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *types.MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body      *ResharingMsgBody    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature []byte               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ParsedRsMessage) Reset() {
	*x = ParsedRsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg20_types_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedRsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedRsMessage) ProtoMessage() {}

func (x *ParsedRsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gg20_types_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedRsMessage.ProtoReflect.Descriptor instead.
func (*ParsedRsMessage) Descriptor() ([]byte, []int) {
	return file_gg20_types_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ParsedRsMessage) GetHeader() *types.MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedRsMessage) GetBody() *ResharingMsgBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ParsedRsMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_gg20_types_messages_proto protoreflect.FileDescriptor

var file_gg20_types_messages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x67, 0x32, 0x30, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x73, 0x76,
	0x2e, 0x67, 0x67, 0x32, 0x30, 0x1a, 0x18, 0x64, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2d, 0x0a, 0x0b, 0x4b, 0x47, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x73, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x54,
	0x0a, 0x0b, 0x4b, 0x47, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73, 0x67, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x46, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x4b, 0x47, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33,
	0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x75, 0x0a, 0x0b, 0x4b, 0x47, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xcb, 0x01, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x73, 0x67, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x4b, 0x47,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x4b, 0x47, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32,
	0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x4b, 0x47, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x33, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x12,
	0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x4b, 0x47, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x22, 0x92,
	0x01, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x4b, 0x47, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32,
	0x30, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0x2d, 0x0a, 0x0b, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d,
	0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73,
	0x67, 0x22, 0x54, 0x0a, 0x0b, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d, 0x73, 0x67,
	0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x62, 0x6c, 0x69, 0x6e,
	0x64, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x73, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x75, 0x0a, 0x0b,
	0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xfd, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e,
	0x67, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67,
	0x67, 0x32, 0x30, 0x2e, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x73, 0x67, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67,
	0x32, 0x30, 0x2e, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x73, 0x67, 0x52, 0x06,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32,
	0x30, 0x2e, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x33, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30,
	0x2e, 0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x34, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e,
	0x52, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x35, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x52, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x73, 0x76, 0x2e, 0x64, 0x6b,
	0x67, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x73,
	0x76, 0x2e, 0x67, 0x67, 0x32, 0x30, 0x2e, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67,
	0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67,
	0x67, 0x32, 0x30, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gg20_types_messages_proto_rawDescOnce sync.Once
	file_gg20_types_messages_proto_rawDescData = file_gg20_types_messages_proto_rawDesc
)

func file_gg20_types_messages_proto_rawDescGZIP() []byte {
	file_gg20_types_messages_proto_rawDescOnce.Do(func() {
		file_gg20_types_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_gg20_types_messages_proto_rawDescData)
	})
	return file_gg20_types_messages_proto_rawDescData
}

var file_gg20_types_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gg20_types_messages_proto_goTypes = []interface{}{
	(*KGRound1Msg)(nil),         // 0: ssv.gg20.KGRound1Msg
	(*KGRound2Msg)(nil),         // 1: ssv.gg20.KGRound2Msg
	(*KGRound3Msg)(nil),         // 2: ssv.gg20.KGRound3Msg
	(*KGRound4Msg)(nil),         // 3: ssv.gg20.KGRound4Msg
	(*KeygenMsgBody)(nil),       // 4: ssv.gg20.KeygenMsgBody
	(*ParsedKGMessage)(nil),     // 5: ssv.gg20.ParsedKGMessage
	(*RsRound1Msg)(nil),         // 6: ssv.gg20.RsRound1Msg
	(*RsRound2Msg)(nil),         // 7: ssv.gg20.RsRound2Msg
	(*RsRound3Msg)(nil),         // 8: ssv.gg20.RsRound3Msg
	(*RsRound4Msg)(nil),         // 9: ssv.gg20.RsRound4Msg
	(*RsRound5Msg)(nil),         // 10: ssv.gg20.RsRound5Msg
	(*ResharingMsgBody)(nil),    // 11: ssv.gg20.ResharingMsgBody
	(*ParsedRsMessage)(nil),     // 12: ssv.gg20.ParsedRsMessage
	(*types.MessageHeader)(nil), // 13: ssv.dkg.types.MessageHeader
}
var file_gg20_types_messages_proto_depIdxs = []int32{
	0,  // 0: ssv.gg20.KeygenMsgBody.round1:type_name -> ssv.gg20.KGRound1Msg
	1,  // 1: ssv.gg20.KeygenMsgBody.round2:type_name -> ssv.gg20.KGRound2Msg
	2,  // 2: ssv.gg20.KeygenMsgBody.round3:type_name -> ssv.gg20.KGRound3Msg
	3,  // 3: ssv.gg20.KeygenMsgBody.round4:type_name -> ssv.gg20.KGRound4Msg
	13, // 4: ssv.gg20.ParsedKGMessage.header:type_name -> ssv.dkg.types.MessageHeader
	4,  // 5: ssv.gg20.ParsedKGMessage.body:type_name -> ssv.gg20.KeygenMsgBody
	6,  // 6: ssv.gg20.ResharingMsgBody.round1:type_name -> ssv.gg20.RsRound1Msg
	7,  // 7: ssv.gg20.ResharingMsgBody.round2:type_name -> ssv.gg20.RsRound2Msg
	8,  // 8: ssv.gg20.ResharingMsgBody.round3:type_name -> ssv.gg20.RsRound3Msg
	9,  // 9: ssv.gg20.ResharingMsgBody.round4:type_name -> ssv.gg20.RsRound4Msg
	10, // 10: ssv.gg20.ResharingMsgBody.round5:type_name -> ssv.gg20.RsRound5Msg
	13, // 11: ssv.gg20.ParsedRsMessage.header:type_name -> ssv.dkg.types.MessageHeader
	11, // 12: ssv.gg20.ParsedRsMessage.body:type_name -> ssv.gg20.ResharingMsgBody
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gg20_types_messages_proto_init() }
func file_gg20_types_messages_proto_init() {
	if File_gg20_types_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gg20_types_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KGRound1Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KGRound2Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KGRound3Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KGRound4Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeygenMsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedKGMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsRound1Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsRound2Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsRound3Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsRound4Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsRound5Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResharingMsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg20_types_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedRsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gg20_types_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gg20_types_messages_proto_goTypes,
		DependencyIndexes: file_gg20_types_messages_proto_depIdxs,
		MessageInfos:      file_gg20_types_messages_proto_msgTypes,
	}.Build()
	File_gg20_types_messages_proto = out.File
	file_gg20_types_messages_proto_rawDesc = nil
	file_gg20_types_messages_proto_goTypes = nil
	file_gg20_types_messages_proto_depIdxs = nil
}
